from datetime import timedelta, timezone

DEXCOM_TIMEZONE_OFFSET = timezone(timedelta(days=-1, seconds=68400))

MIN_GAP_THRESHOLD = 10
SIGNIFICANT_GAP_THRESHOLD = 15

HIGH_GLUCOSE_THRESHOLD = 180
LOW_GLUCOSE_THRESHOLD = 50
IN_RANGE_FLOOR = 50
IN_RANGE_CEILING = 180

A1C_NUMERATOR_CONSTANT = 46.7
A1C_DENOMINATOR_CONSTANT = 28.7

MINUTES_PER_INTERVAL = 5
AGP_INTERVALS_PER_DAY = 24 * 60 // MINUTES_PER_INTERVAL

AGP_OUTLIER_QUANTILES = 20
AGP_VERY_LOW_INDEX = 1
AGP_VERY_HIGH_INDEX = 17
AGP_CRITICAL_LOW_INDEX = 0
AGP_CRITICAL_HIGH_INDEX = 18

AGP_LOWER_QUARTILE = 0
AGP_MEDIAN = 1
AGP_UPPER_QUARTILE = 2
