"""add low and high columns to daily time in range table

Revision ID: 0b0618920932
Revises: 1a8de21cfdc8
Create Date: 2024-12-06 23:19:46.521814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0618920932'
down_revision = '1a8de21cfdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_time_in_range', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeHigh', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timeLow', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_time_in_range', schema=None) as batch_op:
        batch_op.drop_column('timeLow')
        batch_op.drop_column('timeHigh')

    # ### end Alembic commands ###
