"""add trend arrow

Revision ID: 1a8de21cfdc8
Revises: 8ceed636e0b9
Create Date: 2024-11-25 03:29:51.048570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8de21cfdc8'
down_revision = '8ceed636e0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trendArrow', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_column('trendArrow')

    # ### end Alembic commands ###
